# Generated by Django 4.2.9 on 2024-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
